name: Parent POMs merge request workflow
on:
  push:
    branches:
      - "vc-reusable"
      - "!master"
    paths-ignore:
      - .github/**

  workflow_dispatch:
    inputs:
      modules_to_build:
        required: true
        description: "The modules to build when running from the root of the project. Defaults to everything ('.')"
        default: "."

jobs:

  merge-reusable-workflow:
    uses: pentaho/action-common/.github/workflows/merge.yml@master
    with:
      version: "9.5.1.1"
      base_version: "9.5.0.0-240"
      slack_channels: "yukon-test"
      sonar_project_key: "org.pentaho:pentaho-parent-pom"
