name: Parent POMs merge request workflow
on:
  push:
    branches:
      - "actions-minion"
      - "!master"
    paths-ignore:
      - .github/**

  workflow_dispatch:
    inputs:
      modules_to_build:
        required: true
        description: "The modules to build when running from the root of the project. Defaults to everything ('.')"
        default: "."
      build_cmd:
        description: 'Build command'
      test_cmd:
        description: 'Test command'
      release_version:
        required: true
        description: 'Version to be set and built'
      build_number:
        required: true
        description: 'Orchestration Build number'

jobs:

  reusable-merge-workflow:
    uses: pentaho/actions-common/.github/workflows/merge.yml@actions-minion
    with:
      version: "${{ inputs.release_version }}-${{ inputs.build_number }}"
      base_version: "9.5.0.0-240"
      slack_channels: ""
      sonar_project_key: "org.pentaho:pentaho-parent-pom"
      modules_to_build: "${{ inputs.modules_to_build }}"
      build_cmd: "${{ inputs.build_cmd }}"
      test_cmd: "${{ inputs.test_cmd }}"
    secrets: inherit
