name: Parent POMs pull request workflow
on:
  pull_request:
    branches-ignore:
      - master

jobs:

  reusable-pr-workflow:
    uses: pentaho/actions-common/.github/workflows/pr.yml@master
    with:
      slack_channels: "yukon-test"
      sonar_project_key: "org.pentaho:pentaho-parent-pom"
    secrets: inherit
